# Update the loader version on the Index
name: Upload release info

on:
  # trigger when a new release is released
  release:
    types:
      - published

jobs:
  publish:
    name: Upload release info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release data
        id: release-data
        run: python ${{ github.workspace }}/.github/scripts/parse-release.py

      - name: Create release
        shell: bash
        run: |
          CODE=`curl -d '{"prerelease": ${{ github.event.release.prerelease }}, "commit_hash": "${{ github.sha }}", "tag": "${{ github.event.release.tag_name }}", "gd": ${{ steps.release-data.outputs.PLATFORM_INFO }}}' \
            --write-out "%{http_code}" \
            --silent \
            --output /dev/null \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.GEODE_INDEX_TOKEN }}" \
            "https://api.geode-sdk.org/v1/loader/versions"`

          if [ $CODE != "204" ]
          then
            echo "Request failed with response $CODE"
            exit 1
          fi
